### ISSUE TITLE
该项目支持青龙面板部署吗

### ISSUE THREAD

**Issue by yjmm10** [vv314/actions-mtz-coupons#14]
我自己有个云服务器，用docker安装了青龙面板，不知道该项目要如何运行在青龙面板呢

**Comment by vv314** [comment]
这个还未具体研究过，理论上与其他脚本配置步骤是类似的：
1. 拉取仓库代码，指定脚本运行的主文件 `index.js`
2. 找到设置“环境变量”的地方，填入相关信息
3. 配置时任务

**Comment by SouthernDreamS6** [comment]
直接拖到青龙下面手动添加task就行了
不是脚本适配青龙
是青龙能适配各种脚本
