### ISSUE TITLE
作者大哥 能不能做一个多账户配置

### ISSUE THREAD

**Issue by 76236082** [vv314/actions-mtz-coupons#2]
作者大哥 能不能做一个多账户配置，
还有就是能不能增加一个server酱推送~
在这里，先谢谢大哥的公开库~

**Comment by vv314** [comment]
server 酱推送在进行中了。
多账户配置，涉及到任务单元问题：
- 如果希望每个账户独立领取，独立推送。建议 clone 项目，push 到新仓库中，作为新的 action 部署
- 如果不要求每个账户的领取结果独立推送，计划的方案是【主从账户】

**主从账户**
1. 主账户为默认必填项，全局只能有一个主账户
2. 主账户下可以有多个从属账户，从账户可以分别执行领取任务
3. 主账户的领取结果为最终结果，消息推送仅下发给主账户

**Comment by 76236082** [comment]
很高兴收到您的回复！！^_^
我的需求就是您提到的主从账户。
感谢您给我提供了解决方案。通过clone方式已经可以满足我的需求了。
我以为通过token使用json数组的方式 分别按顺序执行任务。
推送消息的话，都推送给主账号的service酱就行。
