### ISSUE TITLE
关于npm run sync命令同步

### ISSUE THREAD

**Issue by Pauluooooo** [vv314/actions-mtz-coupons#30]
在教程脚本更新里面使用npm run sync命令同步的详细步骤是怎么样的，我是小白😂😂

**Comment by vv314** [comment]
项目 Fork 后，Github 将在你名下创建一个同名（actions-mtz-coupons）的仓库。
`npm run sync` 命令简单封装了 Fetch upstream 操作，也可以通过 Github Web UI 界面手动操作，详见 Github 官方文档中的 [同步复刻](https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) 章节。

`npm run sync` 的详细使用方法如下：
1. 打开命令行终端，使用 `git clone` 命令，将你名下的 actions-mtz-coupons 仓库 clone 到本地
2. 将终端的当前路径切换到 actions-mtz-coupons 目录内
3. 输入 `npm run sync` 命令并执行
