### ISSUE TITLE
出现这个代码，然后pushplus不推送咋弄，大佬们😘

### ISSUE THREAD

**Issue by palmcivetcn** [vv314/actions-mtz-coupons#34]
grab couponNode.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-node, actions/checkout

**Comment by vv314** [comment]
github actions 中 node 12 已经弃用了，最新版使用了 node 16，可以按照[此说明](https://github.com/vv314/actions-mtz-coupons#%E4%BA%8C-%E8%84%9A%E6%9C%AC%E6%9B%B4%E6%96%B0)同步上游仓库，或将原项目删除，重新 fork 一份
