### ISSUE TITLE
领取失败: 系统繁忙, 请稍后再试

### ISSUE THREAD

**Issue by TomyJan** [vv314/actions-mtz-coupons#41]
![image](https://user-images.githubusercontent.com/67973160/219958079-69b3cc2e-09d9-4b24-b9a4-d1db0f1215d0.png)

我不知道如何调试, 看了下debug和dev分支都很旧, 不知道是否有用
这是debug 分支的报错
![image](https://user-images.githubusercontent.com/67973160/219958187-0b4d992e-674b-4dad-b564-e94e45fab3d0.png)

感谢大佬

**Comment by vv314** [comment]
报错问题已修复。程序调试请参照 [ 开发与测试](https://github.com/vv314/actions-mtz-coupons#%E4%B8%89-%E5%BC%80%E5%8F%91%E4%B8%8E%E6%B5%8B%E8%AF%95)，推荐在 main 分支运行

**Comment by TomyJan** [comment]
感谢开发大大
