### ISSUE TITLE
程序异常 { code: 2, api: 'gundamGrabV3', msg: '系统繁忙，请稍后再试' }

### ISSUE THREAD

**Issue by jiuchu** [vv314/actions-mtz-coupons#42]
程序异常 { code: 2, api: 'gundamGrabV3', msg: '系统繁忙，请稍后再试' }

**Comment by dfbb9216** [comment]
程序异常 {
  code: 2,
  api: 'gundamGrabV3',
  msg: '找不到请求路径: no matched api config found: [mediacps.meituan.com/gundam/gundamGrabV3](http://mediacps.meituan.com/gundam/gundamGrabV3) at server: com.sankuai.apigw.tsp.default'
}

😦 领取失败
