### ISSUE TITLE
已失效

### ISSUE THREAD

**Issue by jiuchu** [vv314/actions-mtz-coupons#43]
程序异常 {
  code: 2,
  api: 'gundamGrabV3',
  msg: '找不到请求路径: no matched api config found: mediacps.meituan.com/gundam/gundamGrabV3 at server: com.sankuai.apigw.tsp.default'
}

😦 领取失败

**Comment by dfbb9216** [comment]
![QQ截图20230227142119](https://user-images.githubusercontent.com/64184911/221489426-205db0e9-c0d2-4c88-904f-9ad9d24684b5.png)
OK,已经复活。可以手动更新文件或者重新fork，我手动的。
