### ISSUE TITLE
请问作者这个项目还可以使用吗?

### ISSUE THREAD

**Issue by GEM123668** [vv314/actions-mtz-coupons#45]

**Comment by vv314** [comment]
可以使用

**Comment by GEM123668** [comment]
> 可以使用

没看明白name里面的token和value里面的token一样吗

**Comment by vv314** [comment]
name 填固定字符串 "TOKEN"
value 对应真实的值，填从 cookie 抓取到的 token 信息

**Comment by GEM123668** [comment]
> name 填固定字符串 "TOKEN" value 对应真实的值，填从 cookie 抓取到的 token 信息

好的谢谢作者我可以使用了,但是还有一个问题,这个可以领取到25-12的券吗
