### ISSUE TITLE
github actions 输出程序错误 , 程序异常 TypeError: Cannot read properties of undefined (reading 'statusText')

### ISSUE THREAD

**Issue by MagicStarTrace** [vv314/actions-mtz-coupons#46]
![image](https://user-images.githubusercontent.com/15685376/233818009-08a56cb5-cac6-4018-89ef-722fc976dd31.png)
之前都是好的，是账号被风控了？还是需要调整什么？

**Comment by vv314** [comment]
可能是美团的接口有变更，我这几天看下

**Comment by MagicStarTrace** [comment]
> 可能是美团的接口有变更，我这几天看下

已经恢复了，又正常了
