### ISSUE TITLE
token获取获取不到了

### ISSUE THREAD

**Issue by SJH090** [vv314/actions-mtz-coupons#50]
![20230901113849](https://github.com/vv314/actions-mtz-coupons/assets/105922759/23dc76e8-9bb1-4709-a54b-299a2f0d517f)

chrome 访问 i.meituan.com
之前都是直接登录的，今天突然提示”请求异常，拒绝操作“，反复试了几次都是如此
账号是正常的，手机浏览器正常登录

**Comment by zinc1234596** [comment]
用手机扫码link里面copy token吧

**Comment by vv314** [comment]
可以尝试手动清除站点 cookie 后重新登录，或使用 Firefox 浏览器试试
