### ISSUE TITLE
领取失败？token换了也不行

### ISSUE THREAD

**Issue by MagicStarTrace** [vv314/actions-mtz-coupons#51]
![image](https://github.com/vv314/actions-mtz-coupons/assets/15685376/053d5332-e5a2-48b9-ae85-3881b8602e9c)

**Comment by vv314** [comment]
v1.9.0 已修复

**Comment by MagicStarTrace** [comment]
> v1.9.0 已修复

美团首页现在没有登陆入口了？

**Comment by vv314** [comment]
参考 [获取 Token](https://github.com/vv314/actions-mtz-coupons/blob/main/docs/%E8%8E%B7%E5%8F%96token.md)
