### ISSUE TITLE
又不行了？

### ISSUE THREAD

**Issue by MagicStarTrace** [vv314/actions-mtz-coupons#53]
接口异常 ***
  code: 'FETCH_ERROR',
  url: 'https://mediacps.meituan.com/gundam/gundamGrabV4',
  msg: 'Forbidden'
***

**Comment by dfbb9216** [comment]
同样的提示

**Comment by vv314** [comment]
官方对红包接口做了签名校验，破解难度较大。

**Comment by dfbb9216** [comment]
> 官方对红包接口做了签名校验，破解难度较大。

加油啊，大佬。这个库给我省了不少钱

**Comment by MagicStarTrace** [comment]
> 官方对红包接口做了签名校验，破解难度较大。

实在不行 走公众号模拟请求呢？

**Comment by banghha** [comment]
加油

**Comment by vv314** [comment]
进度在 80%，顺利的话，会在一两周内发布。

**Comment by dfbb9216** [comment]
> 进度在 80%，顺利的话，会在一两周内发布。

niubi

**Comment by XC-Hsm** [comment]
我也懂一些js逆向，目前有什么不好处理的地方吗，要不我们交流一下看能否一起解决一下？

**Comment by vv314** [comment]
最近事情比较忙，大家久等了，v2版现已发布

**Comment by XC-Hsm** [comment]
大佬666 我补了好久环境生成的sign还是错误的

**Comment by dfbb9216** [comment]
牛逼！！！不过现在哪个页面可以获得cookie？i.meituan哪个好像没有登录了

**Comment by dfbb9216** [comment]
大佬牛逼
![Uploading QQ截图20231221091845.jpg…]()

**Comment by dfbb9216** [comment]
大佬牛逼
![QQ截图20231221091845](https://github.com/vv314/actions-mtz-coupons/assets/64184911/30a4df45-8017-4de2-8fa4-bdcdef49fe7a)
