### ISSUE TITLE
【感谢更新！】执行报错了。

### ISSUE THREAD

**Issue by Harteyang** [vv314/actions-mtz-coupons#56]
**Error:** error This project's package.json defines "packageManager": "yarn@^yarn@1.22.19". However the current global version of Yarn is 1.22.21.

log附上
[Uploading logo.txt…]()

**Comment by vv314** [comment]
可以参考 [更新](https://github.com/vv314/actions-mtz-coupons/blob/main/docs/%E6%9B%B4%E6%96%B0.md) 操作，或删除原仓库，重新 fork 一份
