### ISSUE TITLE
token和浏览器里的是可以对应上的,但是github 的action 就成功过一次 后面就账号 token1: 领取失败: 程序异常  账号 token2: 领取失败: 程序异常

### ISSUE THREAD

**Issue by MagicStarTrace** [vv314/actions-mtz-coupons#58]
![image](https://github.com/vv314/actions-mtz-coupons/assets/15685376/9e9e1db8-52c3-40f3-a42f-b0e27da0e4e4)
![image](https://github.com/vv314/actions-mtz-coupons/assets/15685376/4c508d77-fdf2-4179-85bf-4d309db6d340)

**Comment by cash1674** [comment]
我也是同样的问题，等待大神出来解决bug

**Comment by vv314** [comment]
官方的加密升级了，正在处理

**Comment by dfbb9216** [comment]
被官方针对了，要不整个群

**Comment by vv314** [comment]
已修复
