### ISSUE TITLE
时不时就登录过期怎么解决

### ISSUE THREAD

**Issue by cyuan0114** [vv314/actions-mtz-coupons#62]
在Chrome登录获取到token之后，不时打开telegram查看，发现总是登录过期，这怎么办，只能每次都重新登录一下吗

**Comment by yd-coder** [comment]
白号token一般能保持几周，过期这么快多半是账号风控了，过期的话只能手动替换token暂时没法自动化登录

**Comment by cyuan0114** [comment]
> 白号token一般能保持几周，过期这么快多半是账号风控了，过期的话只能手动替换token暂时没法自动化登录

白号的意思是被风控了的号吗？ 但是我的账号之前一直是正常使用的，没有做过类似本项目的东西，并且我试了两个账号，都是两三天就掉了。  或者被风控是否跟登录的电脑有关系呢？ 比如登录的电脑挂梯子换IP什么的。望解答，谢谢。

**Comment by yd-coder** [comment]
我这边测试的cookie抓的是手机真机浏览器登录的，时效比较久，你可以试试

**Comment by cyuan0114** [comment]
> 我这边测试的cookie抓的是手机真机浏览器登录的，时效比较久，你可以试试

手机上怎么获取cookie呀，我用iOS的Safari和chrome都不能直接查看cookie，只能清除浏览数据但是不能查看。。

**Comment by yd-coder** [comment]
> > 我这边测试的cookie抓的是手机真机浏览器登录的，时效比较久，你可以试试
> 
> 手机上怎么获取cookie呀，我用iOS的Safari和chrome都不能直接查看cookie，只能清除浏览数据但是不能查看。。

ios下个stream 来抓包获取cookie
