### ISSUE TITLE
又不行了

### ISSUE THREAD

**Issue by MagicStarTrace** [vv314/actions-mtz-coupons#64]
![image](https://github.com/vv314/actions-mtz-coupons/assets/15685376/72c1835f-a625-453c-8c63-5e2cc39daf95)

**Comment by cash1674** [comment]
cookies 不到两天就无法登录，这是黑号了还是啥情况

**Comment by dfbb9216** [comment]
API又被封了吧，等作者更新吧

**Comment by always-dare-to-be-a-beginner** [comment]
![image](https://github.com/vv314/actions-mtz-coupons/assets/32252162/37af916c-23dc-44c5-9362-694b5bcaf1ac)
应该怎么debug呢？是因为啥原因呢

**Comment by cyuan0114** [comment]
期待作者更新！

**Comment by vv314** [comment]
已更新

**Comment by NOwin111** [comment]
又可以了，哈哈，低调
