### ISSUE TITLE
是不是接口不行了

### ISSUE THREAD

**Issue by whmmy** [vv314/actions-mtz-coupons#65]
接口异常 {
  code: 'FETCH_ERROR',
  url: 'https://mediacps.meituan.com/gundam/gundamGrabV4',
  msg: 'Forbidden'
}

😦 领取失败 (v2.1.0)

**Comment by DaoXi-d-X** [comment]
俺也这样(ㄒoㄒ)

**Comment by MUKAPP** [comment]
+1

**Comment by vv314** [comment]
已更新

**Comment by MUKAPP** [comment]
> 已更新

佬，我这里成功一次之后就接口异常了，还是上面的报错
